[project]
name = "search-scraper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx[http2]>=0.28.1",
    "lxml>=6.0.0",
    "pydantic>=2.11.7",
    "pyyaml>=6.0.2",
]

[tool.ruff]
line-length = 100
target-version = "py313"
select = [
    "ALL",
]
ignore = [
    "PLR0913",
    "T201",
    "COM812",
    "DTZ001",
    "S311",
    "D212",
]
[tool.ruff.format]
skip-magic-trailing-comma = false
quote-style = 'single'
[tool.ruff.lint]
flake8-quotes = {inline-quotes = "single"}
